---
name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  release:
    uses: riccione/github-workflows/.github/workflows/rust-release.yml@24ba5409c1eeac121965cedc2fb507b0387f25af
